### PR TITLE
Allow logger customization

### PR DESCRIPTION
**Pull request by medikoo**
Configures logs to be output via `log4` dependency. Removes `verbose` option.

It needs to come with major version bump (as after that for logs to be seen some log4 output engine needs to be loaded).

### CODE REVIEW

**Comment by medikoo** [comment]
Tests fails due to bug in them, #16 fixes that

**Comment by laurisvan** [comment]
Looks good! I'm not yet fully sure if this is the best way to inject logging in the future, but if we find out a better way, we'll change it.

**Comment by medikoo** [comment]
Thanks @laurisvan! It'll be good publish it, I think it's wise to bump major. Let me know, then I'll update MTB PR with new version

**Comment by laurisvan** [comment]
This is incremental, so I'll only bump the minor. That'll be 0.9.

**Comment by medikoo** [comment]
Sure, I didn't notice it's 0.x

**Pull request merged**
